### ISSUE TITLE
Request format GeoJson / Shapefile.

### ISSUE THREAD

**Issue by saberknight35** [kulikode-dev/peta-indonesia-terbaru-38-provinsi#1]
Dear Tim Kulikode, 

Bisa request untuk format geojson atau shapefilenya?

Thanks.

**Comment by kulikode-dev** [comment]
Dear @saberknight35 

Untuk format GeoJSON dan SHP Filenya akan direlease dan diupdate kembali apabila sudah ada.

Best Regards.

**Comment by kulikode-dev** [comment]
> Dear Tim Kulikode,
> 
> Bisa request untuk format geojson atau shapefilenya?
> 
> Thanks.

**Updated 23 Des 2024:** 
Peta Indonesia Provinsi, Kabupaten dan Kota dalam format GeoJSON (versi 34 Provinsi) telah ditambahkan pada link folder. Terima kasih
